name: macOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  make:
    strategy:
      matrix:
        os: [macos-10.15]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Download SSL certificates'
        run: wget --no-verbose https://curl.se/ca/cacert.pem
      - name: 'Check file'
        run: ls -la /Users/runner/work/ruby-packer/ruby-packer/cacert.pem
      # - uses: actions/checkout@v2
      # - name: "[Enclose.IO] Install dependencies"
      #   run: |
      #     brew upgrade
      #     brew install squashfs
      # - name: "[Enclose.IO] Check dependencies"
      #   run: |
      #     sw_vers
      #     uname -a
      #     uname -p
      #     uname -m
      #     sysctl -n machdep.cpu.brand_string
      #     which mksquashfs
      #     mksquashfs -version
      # - name: "[Enclose.IO] Set up Ruby"
      #   uses: ruby/setup-ruby@v1
      # - name: "[Enclose.IO] Install rubocop"
      #   run: gem install rubocop
      # - name: "[Enclose.IO] Run rubocop"
      #   run: rubocop
      # - name: "[Enclose.IO] Install dependencies"
      #   run: bundle install
      # - name: "[Enclose.IO] Rake"
      #   env:
      #     SSL_CERT_FILE: "/Users/runner/work/ruby-packer/ruby-packer/cacert.pem"
      #   run: bundle exec rake
      # - name: "[Enclose.IO] Create macOS Release"
      #   if: ${{ github.ref == 'refs/heads/master' && success() }}
      #   id: create_macos_release
      #   uses: pmq20/create-release@delete-old-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: darwin-x64
      #     release_name: Latest macOS Pre-release
      #     draft: false
      #     prerelease: true
      #     replace_old_tag: true
      # - name: "[Enclose.IO] Upload macOS Release"
      #   if: ${{ github.ref == 'refs/heads/master' && success() }}
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_macos_release.outputs.upload_url }}
      #     asset_path: ./rubyc
      #     asset_name: rubyc
      #     asset_content_type: application/octet-stream
